<a href="https://colab.research.google.com/github/DaryaTereshchenko/ukr/blob/main/Glove_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.utils import to_categorical
import tensorflow as tf
from keras.models import Model
from keras.layers import Dense, Flatten, Input, Dropout, Embedding, BatchNormalization
from sklearn.model_selection import train_test_split

In [ ]:
import pickle
import pandas as pd
import numpy as np

In [ ]:
filename = "/content/drive/MyDrive/emb.pickle"
with open(filename, 'rb') as f:
    classification_dict = pickle.load(f)

In [ ]:
df = pd.DataFrame(classification_dict)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,44991,44992,44993,44994,44995,44996,44997,44998,44999,source
0,0.289065,-0.302258,-0.067125,-0.142829,-0.571341,-0.247752,-0.647140,-0.315832,-0.309583,0.056869,...,-0.062587,0.220745,0.188114,-0.219599,0.187794,-0.533731,0.141170,-0.203350,0.103120,2
1,0.107319,-0.163065,-0.572483,-0.187558,0.308994,0.008620,-0.755999,0.303792,-0.714780,0.386464,...,0.182555,0.053285,0.197741,-0.467305,0.795056,-0.307584,0.037243,0.173997,-0.184379,3
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.293032,0.042476,0.620857,-0.338957,0.628428,-0.500935,-0.217840,0.239745,-0.007407,3
3,0.639948,0.139452,-0.255787,0.325295,-0.217746,0.383579,0.142693,-0.187305,0.103691,0.258715,...,-0.453204,0.287243,-0.354645,0.239500,-0.215203,-0.056409,0.205022,0.159679,-0.440074,2
4,-0.179089,-0.271164,-0.179615,-0.101294,-0.351352,-0.237466,-0.519836,0.181826,-0.415627,-0.777196,...,0.081289,-0.448468,-0.023365,-0.410670,-0.664822,-0.677202,0.071613,0.081858,-0.489330,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25672,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.133993,0.431885,-0.373035,-0.187254,-0.400546,0.641448,0.211965,-0.133053,0.394565,1
25673,-0.011475,-0.362595,0.400265,-0.096101,0.508484,0.030144,-0.127819,-0.825140,0.263326,0.011580,...,-0.009434,0.190915,-0.211210,0.443357,-0.651554,-0.401812,-0.788020,-0.321245,-0.436221,2
25674,-0.083649,-0.256452,-0.117438,0.246674,-1.133102,-0.857174,-0.106594,0.375665,0.361931,0.167915,...,-0.019849,0.060704,-0.539611,-0.321925,-0.482078,0.295565,-0.239073,0.281052,-0.128144,3
25675,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.178413,0.102045,0.460402,0.688739,0.330359,-0.024408,-0.240008,0.013830,-0.491883,2
25676,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.153855,-0.212703,0.066017,0.031176,-0.014382,0.051882,0.020979,0.220616,0.344161,0

In [ ]:
X = df.drop(["source"], axis=1)
y = df["source"]

In [ ]:
y

0        2
1        3
2        3
3        2
4        3
        ..
25672    1
25673    2
25674    3
25675    2
25676    0
Name: source, Length: 25677, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=66)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.1, random_state=66)

In [ ]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,44990,44991,44992,44993,44994,44995,44996,44997,44998,44999
4672,-0.222050,0.009319,-0.496519,0.151339,0.363078,0.753875,0.343831,0.291333,0.192254,-0.447469,...,0.079450,-0.924703,0.137032,0.371684,-0.582917,0.365376,-0.421869,0.095882,0.233255,-0.595066
23707,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.458558,-0.411015,0.597362,-0.132639,0.300550,-0.334185,-0.357574,-0.118268,0.411162,0.012713
2844,0.025248,-0.000363,-0.399136,0.173238,0.243948,0.092935,0.242948,0.149090,-0.230439,0.096127,...,0.664864,-0.253170,-0.432061,0.295912,-0.020221,0.613019,0.357955,-0.057863,0.255735,0.396173
134,0.061691,-0.286619,0.404135,0.106467,-0.301602,-0.000422,0.334202,0.042994,0.341396,0.152641,...,-0.830375,-0.764881,-0.051596,-0.061358,0.002064,-0.546854,-0.093395,-0.431758,0.166619,-0.344096
21282,0.219192,0.245972,-0.103993,-0.270394,0.460076,0.251507,-0.225525,0.151618,-0.452140,0.193533,...,0.050052,0.256063,0.466831,0.029310,-0.383633,-0.005059,0.472591,0.072383,-0.435446,-0.098086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18125,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.215444,0.161188,-0.602980,0.199637,0.191927,-0.469873,-0.199175,-0.006580,0.406361,0.059453
8243,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.079450,-0.924703,0.137032,0.371684,-0.582917,0.365376,-0.421869,0.095882,0.233255,-0.595066
8823,0.113656,-0.265928,-0.022830,0.191896,0.599909,-0.068728,0.569458,0.157713,0.297890,0.049503,...,0.046069,0.193703,-0.058200,-0.227618,0.076325,0.398522,-0.386737,-0.330183,0.697512,-0.151958
25404,-0.255687,-0.225674,-0.258366,0.274693,-0.530939,-0.685399,0.091413,0.400342,-0.058255,0.277004,...,0.634943,0.036611,0.181321,0.480992,-0.650417,-0.380342,0.273784,0.164587,-0.477687,0.125393
25620,0.263540,-0.636374,-0.690902,0.477543,-0.038909,-0.336828,0.337736,0.045989,-0.156252,-0.038493,...,0.274874,0.147574,-0.065204,0.210010,-0.354988,-0.279106,-0.141509,-0.279829,0.297041,-0.507569

In [ ]:
# Encode the categories
y_train = to_categorical(np.asarray(y_train), dtype ="uint8")
y_test = to_categorical(np.asarray(y_test), dtype ="uint8")
y_val = to_categorical(np.asarray(y_val), dtype ="uint8")

In [ ]:
y_train = y_train.argmax(axis=1)

In [ ]:

y_test = y_test.argmax(axis=1)
y_val =  y_val.argmax(axis=1)

In [ ]:
MAX_WORS = 150

In [ ]:
def build_model():
    i = Input(shape=(45000), dtype=tf.float32)
    
    # x = Flatten()(i)
    output = Dense(4, activation='softmax')(i)

    model = Model(inputs=i, outputs=output)

    model.compile(optimizer="Adam", loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
    metrics=["accuracy"])
    return model

In [ ]:
model = build_model()
model.summary()

In [ ]:
model.fit(X_train, y_train, batch_size = 32, epochs = 10, verbose=1, validation_data=(X_val, y_val))

In [ ]:
y_pred = model.predict(X_test).argmax(axis=1)
y_pred_one_hot = to_categorical(np.asarray(y_pred), dtype ="uint8")

In [ ]:
from sklearn.metrics import classification_report, accuracy_score
print("=== Classification Report ===")
print(classification_report(y_test, y_pred_one_hot))
print('\n')
print("=== Accuracy Score ===")
print(accuracy_score(y_test, y_pred_one_hot))

In [ ]:
y_test = np.asarray(y_test).argmax(axis=1)

In [ ]:
from pathlib import Path
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
import matplotlib.pyplot as plt


def plot_cm(y_true, y_pred, normalize,
    labels=None,
    save=False,
    directory=None,
    filename=None,
    title="",
    cmap=plt.cm.Blues,
):
    cm = confusion_matrix(y_true, y_pred, normalize=normalize)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    disp.plot(cmap=cmap)
    plt.title(title)
    plt.show()

In [ ]:
plot_cm(y_test, y_pred, 'true')